namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task report: :environment do
    require "simplecov-cobertura"
    require "simplecov_json_formatter"

    SimpleCov.collate(Dir["coverage_results/.resultset-*.json"], "rails") do
      formatter SimpleCov::Formatter::MultiFormatter.new([
        SimpleCov::Formatter::JSONFormatter,
        SimpleCov::Formatter::HTMLFormatter,
        SimpleCov::Formatter::CoberturaFormatter
      ])
    end
  end
end
