# frozen_string_literal: true

require "rails_helper"
require "faker"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe("/expense_accounts") do
  # This should return the minimal set of attributes required to create a valid
  # ExpenseAccount. As you add validations to ExpenseAccount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: Faker::Commerce.product_name
    }
  end

  let(:invalid_attributes) do
    {
      name: nil
    }
  end

  before do
    create_account
    login
  end

  describe "GET /index" do
    it "renders a successful response" do
      ExpenseAccount.create!(valid_attributes)
      get expense_accounts_url
      expect(response).to(be_successful)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      expense_account = ExpenseAccount.create!(valid_attributes)
      get expense_account_url(expense_account)
      expect(response).to(be_successful)
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_expense_account_url
      expect(response).to(be_successful)
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      expense_account = ExpenseAccount.create!(valid_attributes)
      get edit_expense_account_url(expense_account)
      expect(response).to(be_successful)
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExpenseAccount" do
        expect do
          post(expense_accounts_url, params: {expense_account: valid_attributes})
        end.to(change(ExpenseAccount, :count).by(1))
      end

      it "redirects to the created expense_account" do
        post expense_accounts_url, params: {expense_account: valid_attributes}
        expect(response).to(redirect_to(expense_account_url(ExpenseAccount.last)))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExpenseAccount" do
        expect do
          post(expense_accounts_url, params: {expense_account: invalid_attributes})
        end.not_to(change(ExpenseAccount, :count))
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post expense_accounts_url, params: {expense_account: invalid_attributes}
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        {
          name: Faker::Commerce.product_name
        }
      end

      it "updates the requested expense_account" do
        expense_account = ExpenseAccount.create!(valid_attributes)
        patch expense_account_url(expense_account), params: {expense_account: new_attributes}
        expense_account.reload
        expect(expense_account.name).to eq(new_attributes[:name])
      end

      it "redirects to the expense_account" do
        expense_account = ExpenseAccount.create!(valid_attributes)
        patch expense_account_url(expense_account), params: {expense_account: new_attributes}
        expense_account.reload
        expect(response).to(redirect_to(expense_account_url(expense_account)))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        expense_account = ExpenseAccount.create!(valid_attributes)
        patch expense_account_url(expense_account), params: {expense_account: invalid_attributes}
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested expense_account" do
      expense_account = ExpenseAccount.create!(valid_attributes)
      expect do
        delete(expense_account_url(expense_account))
      end.to(change(ExpenseAccount, :count).by(-1))
    end

    it "redirects to the expense_accounts list" do
      expense_account = ExpenseAccount.create!(valid_attributes)
      delete expense_account_url(expense_account)
      expect(response).to(redirect_to(expense_accounts_url))
    end
  end
end
