name: "adventure_money"

services:
  rails-app:
    labels:
      - dev.orbstack.domains=advmoney.local
      - dev.orbstack.http-port=3000
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mail:
        condition: service_started
      selenium:
        condition: service_started

  postgres:
    labels:
      - dev.orbstack.domains=db.advmoney.local
    image: postgres:16.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 500ms
      retries: 5
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    labels:
      - dev.orbstack.domains=cache.advmoney.local
    image: redis:7.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 500ms
      retries: 5
    networks:
      - default
    volumes:
      - redis-data:/data

  mail:
    labels:
      - dev.orbstack.domains=mail.advmoney.local
      - dev.orbstack.http-port=1080
    image: marlonb/mailcrab:latest
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - default

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
