default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 0.0.0.0
  port: 5432
  username: postgres

development:
  <<: *default
  database: adventure_money_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: adventure_money_test
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
