name: "Coverage"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  coverage:
    concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-lint
    cancel-in-progress: true
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
