name: "Verify"
on:
  push:
    branches:
      - "main"
      - "release/**"
  pull_request:
    branches:
      - "main"
      - "release/**"
jobs:
  linters:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint
      cancel-in-progress: true
    name: Linters
    runs-on: ubuntu-latest
    env:
      CI: true
      RUBY_VERSION: '3.1.2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7 # v1.92
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Run linters
        run: |
          bundle exec rubocop --parallel
          bundle exec erblint --lint-all

      - name: Run security checks
        run: |
          bundle exec bundle audit check --update
          bundle exec brakeman -q -w2 -o tmp/brakeman.html

  tests:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: true
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: adventure
          POSTGRES_PASSWORD: money
          POSTGRES_DB: adventure_money_test
        ports:
          - "5432:5432"
    env:
      CI: true
      RUBY_VERSION: '3.1.2'
      RAILS_ENV: test
      DATABASE_URL: "postgres://adventure:money@0.0.0.0:5432/adventure_money_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7 # v1.92
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Precompile assets
        run: |
          bundle exec rake assets:precompile --trace
          ls /home/runner/work/adventure-money/adventure-money/public/assets

      - name: Set up database
        run: |
          bundle exec rails db:schema:load --trace

      - name: RSpec tests
        run: |
          bundle exec rspec spec

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          failedThreshold: 80
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.actor != 'dependabot[bot]' }}

      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
